# Your Website Title
title: Carl Sin 

# Your Website URL
url: 'http://carlsec.com'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Carl Sin
tagline: CCIE | CISSP | OSCP | Network Architect | Pentester | AI Security | Product Development |
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Network & Cybersecurity & AI All the things      
description_tiny: Record all my learnings
email: hello@carlsec.com
website: carlsec.com# do not add http://
linkedin: carl-sin-83098b73


# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap